- BE/src/main/java/com/codesquad/dust/User.java
- BE/src/main/java/com/codesquad/dust/UserRepository.java
- BE/src/main/resources/schema.sql
- BE/src/test/java/com/codesquad/dust/UserRepositoryTest.java
- 프로젝트 요구사항에 맞게 SpringBoot, Spring JDBC 설정 완료.
> [FEAT] 프로젝트 개발 환경 구축

- FE/.gitignore
- FE/babel.config.js
- FE/package-lock.json
- FE/package.json
- FE/src/javascript/dustCondition/dustCondition.js
- FE/src/javascript/dustForecast/dustForecast.js
- FE/src/javascript/main.js
- FE/src/javascript/navigation/navigation.js
- FE/src/page/index.html
- FE/src/style/common/lib/reset.css
- FE/src/style/common/style.css
- FE/src/style/dustCondition.css
- FE/src/style/dustForecast.css
- FE/src/style/navigation.css
- FE/webpack.config.js
Title >
* FE-Common-001 기능 개발.
Contents >
* 미세먼지 프로젝트에 대한 FrontEnd Side 의 디렉토리 구조 설정.
> [FEAT] #FE-Common-001 기능 개발

- FE/src/javascript/dustCondition/dustCondition.js
- FE/src/javascript/dustForecast/dustForecast.js
- FE/src/javascript/main.js
- FE/src/javascript/navigation/navigation.js
Title >
* 스켈레톤 코드 수정
Content >
* 이벤트 리스너를 등록하는 순서가 fetch 이후가 될 수 있으므로
Component 에서 순서를 조절 할 수 있도록 init 함수 추가.
> [FEAT] 스켈레톤 코드 수정

- FE/src/page/index.html
Title >
* FE-Navigation-001 기능 개발
Contents >
* 네비게이션 탭에 대한 HTML 구현
Related Issue >
* https://github.com/codesquad-member-2020/dust-9/issues/8
> [FEAT] FE-Navigation-001 기능 개발

- FE/src/style/navigation.css
Title >
* FE-Navigation-001 기능 개발
Contents >
* 네비게이션 탭에 대한 CSS 구현
Related Issue >
* https://github.com/codesquad-member-2020/dust-9/issues/9
> [FEAT] FE-Navigation-002 기능 개발

- FE/src/style/dustCondition.css
> [FEAT] FE-DustCondition-002 미세먼지 화면에 대한 CSS 추가

- FE/src/javascript/dustCondition/dustCondition.js
- FE-DustCondition-001에서 작성한 HTML을 렌더링 하는 기능 추가
> [FEAT] FE-DustCondition-003 미세먼지 화면 render 함수 구현

- FE/src/style/navigation.css
- 네비게이션 버튼 배경색 수정
- active CSS를 focus CSS로 변경
> [FEAT] FE-Navigation-002 CSS 스타일 수정

- FE/src/style/dustForecast.css
Titile >
* #FE-DustForecast-002 요구사항 구현
Contents >
* 예보 화면에 대한 css 구현.
> [FEAT] #FE-DustForecast-002 요구사항 구현

- FE/src/javascript/dustForecast/dustForecast.js
Title >
* #FE-DustForecast-003 요구사항 구현.
Contents >
* 예보 화면을 렌더링하는 함수 구현.
> [FEAT] #FE-DustForecast-003 요구사항 구현

- FE/src/javascript/util/fetchrequest.js
Title >
* fetch 유틸 함수 추가
Contents >
* fetch 요청을 위한 함수를 추가.
* url, method, data 를 입력 받을 수 있도록 설정.
> [FEAT] fetch 유틸 함수 추가

- FE/src/javascript/dustForecast/dustForecast.js
Title >
* #FE-DustForecast-004 요구사항 구현.
Contents >
* BE 에 예보/등급 문자를 요청하여 전달받은 다음 렌더링.
> [FEAT] #FE-DustForecast-004 요구사항 구현

- FE/src/javascript/dustForecast/dustForecast.js
Title >
* #FE-DustForecast-005 요구사항 구현.
Contents >
* 서버에 미세먼지 예보에 대한 url 을 요청하여 전달 받은 다음
렌더링 하는 기능.
> [FEAT] #FE-DustForecast-005 요구사항 구현

- FE/src/style/dustCondition.css
- 미세먼지앱 타이틀 부분 CSS 추가
- 타이틀이 추가되면서 다른 요소들 사이즈 조정
> [FEAT] FE-DustCondition-002 CSS 수정

- FE/src/javascript/dustCondition/dustCondition.js
- 미세먼지 앱 타이틀 추가
- 측정소 이름 태그 옆에 ' 측정소 기준' 문구 추가
> [FEAT] FE-DustCondition-003 render 함수 안 html 수정

- FE/src/javascript/dustCondition/dustCondition.js
- 등급에 따라 다른 배경색과 이모지, 등급 이름을 객체에 담아 리턴하는 함수 구현
> [FEAT] FE-DustCondition-004 미세먼지 등급별 디스플레이 세팅 함수 구현

- FE/src/javascript/dustCondition/dustCondition.js
- 현재 위치의 위도, 경도를 URL에 담아 GET 방식으로 서버요청 (아직 정식 서버는 아님)
- 서버로부터 데이터를 받아 가까운 측정소, 현재 시간의 미세먼지 등급을 출력
- 등급별 CSS 스타일도 함께 적용
- setGradeDisplay() 의 switch문에 있는 gradeValue를 string 값으로 변경
> [FEAT} FE-DustCondition-005 미세먼지 등급 출력 기능 구현

- FE/src/javascript/constants/className.js
- FE/src/javascript/dustForecast/dustForecast.js
- FE/src/style/dustForecast.css
Title >
* 예보 화면 기능 구현
Contents >
* Scroll Bar 영역 터치에 대한 기능 구현
* Indicator 드래그에 대한 기능 구현
* Play/Pause 버튼 기능 구현
> 예보 화면 기능 구현

- FE/src/javascript/dustForecast/dustForecast.js
- FE/src/javascript/main.js
- FE/src/javascript/navigation/navigation.js
Title >
* FE-Navigation-003 기능 구현
Contents >
* 네비게이션 탭의 버튼들을 눌렀을 때에 대한 화면전환 기능 구현
> FE-Navigation-003 기능 구현

- FE/src/javascript/dustCondition/dustCondition.js
- FE/src/style/dustCondition.css
- 대기질 기록표시 막대그래프 구현
- 미세먼지 등급별 그래프의 색상 다르게 렌더링
- 그래프 height와 border CSS 스타일 수정
> [FEAT] FE-DustCondition-006 그래프 구현

- FE/.gitignore
- FE/src/javascript/constants/mockUrls.js
- FE/src/javascript/constants/serviceUrls.js
- FE/src/javascript/data/dustForecastData.js
- FE/src/javascript/data/navigationData.js
- FE/src/javascript/dustForecast/controllComponent.js
- FE/src/javascript/dustForecast/dustForecast.js
- FE/src/javascript/dustForecast/forecastImageComponent.js
- FE/src/javascript/dustForecast/informationComponent.js
- FE/src/javascript/navigation/navigation.js
- FE/src/style/dustForecast.css
Title >
* Dust Forecast 리팩토링.
Contents >
* dustForecast.js 에 몰려있는 기능을 의미별로 분류.
* 매직넘버 제거.
* constants js 파일들을 추가.
* navigation 및 dustForecast 에 대한 data 파일들을 추가.
> [FEAT] Dust Forecast 리팩토링

- FE/src/javascript/dustCondition/dustCondition.js
- 스크롤시 그래프의 포인터가 움직이고, 포인터가 가리키는 그래프의 미세먼지 정보가 상단에 출력
> [FEAT] FE-DustCondition-007 그래프 스크롤 이벤트 구현

- FE/src/javascript/constants/forecastCacheInformation.js
- FE/src/javascript/data/dustForecastData.js
- FE/src/javascript/dustForecast/controllComponent.js
- FE/src/javascript/dustForecast/dustForecast.js
- FE/src/javascript/dustForecast/forecastImageComponent.js
- FE/src/javascript/main.js
- FE/src/page/index.html
- FE/src/style/dustForecast.css
Title >
* play / pause 정상동작하지 않았던 문제 수정.
* cache 기능 추가.
Contents >
* Animation 중 scroll 바 클릭시 play/pause 변경되지 않은 문제 수정.
* 기존 css 애니메이션을 rester 이미지로 교체.
* cache 기능 추가.
> [FEAT, BUG] play / pause 정상동작하지 않았던 문제 수정

- FE/src/javascript/dustCondition/dustCondition.js
- 미세먼지 그래프 스크롤시 시간에 따라 '어제','오늘' 날짜 정보를 변경해주는 로직 추가
> [FEAT] 미세먼지 그래프 날짜 변경 기능 추가

- FE/src/javascript/dustCondition/dustCondition.js
- FE/src/javascript/dustCondition/dustGradeSetting.js
- FE/src/javascript/dustCondition/dustGraphComponent.js
- dustCondition.js 에 모여있던 함수들을 의미와 기능별로 분리
> [FEAT] DustCondition 리팩토링

- FE/src/javascript/constants/serviceUrls.js
- FE/src/javascript/dustForecast/dustForecast.js
> [FEAT] 서비스 url 수정

- FE/src/javascript/dustCondition/dustCondition.js
> [FEAT] DustCondition 서비스 URL 수정
